version: 2

refs:
  container: &container
    docker:
      - image: chybie/node-aws-cli
    working_directory: ~/repo
  steps:
    - &Versions
      run:
        name: Versions
        command: |
          node -v && npm -v && yarn -v
          printenv
    - &Restore_Cache
      restore_cache:
        name: Restore Cache
        keys:
          - yarn-packages-{{ checksum "yarn.lock" }}
    - &Save_Cache
      save_cache:
        name: Save Cache
        key: yarn-packages-{{ checksum "yarn.lock" }}
        paths:
          - ~/.cache/yarn
    - &Install
      run:
        name: Install Dependencies
        command: yarn install --frozen-lockfile
    - &Install_Global_Dependencies
      run:
        name: Install Global Dependencies
        command: npm i -g cross-ci commit-status ci-scripts
    - &Setup_Environment
      run:
        name: Setup Environment
        command: |
          echo 'export BUILD_VERSION=$(cross-ci printenv BUILD_VERSION)' >> $BASH_ENV
          echo 'export BUILD_NUM=$(cross-ci printenv BUILD_NUM)' >> $BASH_ENV
          echo 'export PROJECT_NAME=$(cross-ci printenv PROJECT_NAME)' >> $BASH_ENV
          echo 'export GH_STATUS_TOKEN=$(cross-ci printenv GITHUB_TOKEN)' >> $BASH_ENV
    - &Build
      run:
        name: Build
        command: yarn build
    - &Build_Storybook
      run:
        name: Build Storybook
        command: yarn storybook:build
    - &Test
      run:
        name: Test
        command: yarn test
    - &Post_to_GitHub_Storybook_Artifacts_Link
      run:
        name: Post to GitHub Storybook Artifacts Link
        command: npx commit-status success "Storybook" $BUILD_VERSION "https://$BUILD_NUM-172218257-gh.circle-artifacts.com/0/root/repo/storybook-static/index.html"
    - &Post_to_Slack
      run:
        name: Post to Slack
        command: npx ci-scripts slack

jobs:
  all:
    <<: *container
    steps:
      - checkout
      - *Versions
      - *Restore_Cache
      - *Install
      - *Save_Cache
      - *Install_Global_Dependencies
      - *Setup_Environment
      - *Build
      - *Build_Storybook
      - *Test
      - store_artifacts:
          path: ~/repo/storybook-static
      - *Post_to_GitHub_Storybook_Artifacts_Link
      - *Post_to_Slack

  master:
    <<: *container
    steps:
      - checkout
      - *Versions
      - *Restore_Cache
      - *Install
      - *Save_Cache
      - *Install_Global_Dependencies
      - *Setup_Environment
      - *Build
      - *Build_Storybook
      - *Test
      - store_artifacts:
          path: ~/repo/storybook-static
      - *Post_to_GitHub_Storybook_Artifacts_Link
      - *Post_to_Slack
      - run:
          name: Upload Storybook
          command: aws s3 sync ./storybook-static s3://infrastructure.production.ci.onp4.com/builds/nice-ui/master/storybook --acl public-read
      - run:
          name: Post to GitHub Storybook master
          command: npx commit-status success "Storybook" "latest" "https://infrastructure.production.ci.onp4.com.s3.amazonaws.com/builds/nice-ui/master/storybook/index.html"
      - run:
          name: Release
          command: yarn release

  nightly:
    <<: *container
    steps:
      - checkout
      - *Versions
      - *Install
      - *Install_Global_Dependencies
      - *Setup_Environment
      - *Build
      - *Build_Storybook
      - *Test

workflows:
  version: 2
  all:
    jobs:
      - all:
          context: common-env-vars
          filters:
            branches:
              ignore:
                - master
                - gh-pages
  master:
    jobs:
      - master:
          context: common-env-vars
          filters:
            branches:
              only: master
  nightly:
    jobs:
      - nightly:
          context: common-env-vars
    triggers:
      - schedule:
          cron: '0 1 * * *'
          filters:
            branches:
              only: master
